backend:
    name: git-gateway
    branch: master

media_folder: static/img
public_folder: /img

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'posts/blog'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime' }
          - {
                label: 'Tags',
                name: 'category',
                widget: 'list',
                default: ['FrontEnd'],
            }
          - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
          - { label: 'Body', name: 'body', widget: 'markdown' }
